name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        deno: ["v1.15.2"]
      fail-fast: true
    steps:
      - uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: '3.8.2-management-alpine'
          host port: 5672
          rabbitmq user: 'root'
          rabbitmq password: 'password'
          rabbitmq vhost: '/'
      - uses: actions/checkout@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: run tests
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: deno test --reload --allow-all --unstable